name: puffysticks
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  animator: ^0.1.4
  url_launcher: ^5.0.5
  http: ^0.12.0+2
  photo_view: ^0.4.2
  flutter_svg: ^0.13.0
  flutter_advanced_networkimage: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
      - family: Muli
        fonts: 
          - asset: assets/fonts/Muli-Regular.ttf
          - asset: assets/fonts/Muli-RegularItalic.ttf
            style: italic
          - asset: assets/fonts/Muli-Bold.ttf
            weight: 700
          - asset: assets/fonts/Muli-Black.ttf
            weight: 900